---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "graphql.fullname" . }}
  namespace: {{ include "graphql.namespace" . }}
  labels:
    {{- include "graphql.labels" . | nindent 4 }}
type: Opaque
stringData:
  admin-secret: {{ .Values.hasura.env.adminSecret | quote }}
  postgres-password: {{ .Values.postgresql.password | quote }}
