---
{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "graphql.serviceAccountName" . }}
  namespace: {{ include "graphql.namespace" . }}
  labels:
    {{- include "graphql.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
